### ISSUE TITLE
.env.development file not clear in database README

### ISSUE THREAD

**Issue by Dale-Muccignat** [LXCat-project/LXCat#1287]
I was following the product deployment guide t set up a local lxcat databse instance.

I followed the app/readme.md to run `pnpm install` and `pnpm dev` in the root of the git repo but needed a database setup so went to [packages/database/readme.md](https://github.com/LXCat-project/LXCat/blob/3550ee2702a8ba47455dfc04aa5bf621f7c00d66/packages/database/README.md). I created a .env.development file

```
# Optional: URL of the ArangoDB api; usually left as default: http://localhost:8529.
# ARANGO_URL=<URL>
# Optional: Name of the database that hosts LXCat related data. Default: `lxcat`.
ARANGO_DB=lxcat
# Optional: Name of the restricted ArangoDB user used by `app` to communicate to the database. Default: `lxcat`.
ARANGO_USERNAME=lxcat
# Password used by the `ARANGO_USERNAME` user to connect to database
ARANGO_PASSWORD=2145
# ArangoDB root password.
ARANGO_ROOT_PASSWORD=2145
```

However, the next step was to run:
`docker run --rm --volume $PWD/arangodb3:/var/lib/arangodb3 --env-file .env -p 8529:8529 arangodb/arangodb:3.11.0` which gives the error `.env: no such file`

I'm probably missing something silly. I tried changing the command to replace .env with .env.development, which seems to run and I can open the localhost interface but can not log into the database as I get login failed.

Not entirely sure what I might be doing wrong, very new to docker so will see what I can figure out. But if you had any advice that would be appreciated :)

**Comment by daanboer** [comment]
Hi @Dale-Muccignat, good find! I have inspected the readme and you are correct that it is currently not correct. The env file argument should indeed point to the `.env.development` file at the root of the repository (so `../../.env.development` when residing in the `packages/database` directory. To access the ArangoDB dasboard you would then first have to run the `pnpm setup` command to create the database and the user (this is not clear from the readme). I have made some updates to the readme in the `1286-fix-db-readme` branch, could you check whether these changes clarify the process?

**Comment by Dale-Muccignat** [comment]
Thanks @daanboer! Running the commands from `packages/database` fixed it (along with the fixed docker command. I've got the database running now and can log in with lxcat ^_^
