### ISSUE TITLE
Protected endpoints unreachable on the demo instance

### ISSUE THREAD

**Issue by daanboer** [LXCat-project/LXCat#1406]
Issuing a `curl` request to a protected endpoint will present the user with an empty response. To reproduce, try:

```bash
curl https://demo.lxcat.net/api/scat-css
```

which comes up with an empty response. The same request sent to a local dev environment returns the expected `Unauthorized`. The same happens when providing valid credentials through a token. On the other hand, issuing

```bash
curl https://demo.lxcat.net/api/species
```

correctly returns the list of top-level species. When attaching to the docker container running on the LXCat master server, and issuing a request to a protected endpoint presents the following error:

```
 ⨯ "exp" claim timestamp check failed
    at t.default (/code/app/.next/server/chunks/5268.js:1:56631)
    at t.jwtDecrypt (/code/app/.next/server/chunks/5268.js:1:34160)
    at async p (/code/app/.next/server/chunks/5268.js:1:98849)
    at async /code/app/.next/server/chunks/2531.js:1:696
    at async i.callchain (/code/app/.next/server/chunks/2531.js:1:2166)
    at async i.callchain (/code/app/.next/server/chunks/2531.js:1:2166)
    at async i.callchain (/code/app/.next/server/chunks/2531.js:1:2395)
    at async /code/app/.next/server/chunks/2531.js:1:2016
    at async /code/node_modules/.pnpm/next@14.2.13_@playwright+test@1.47.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
    at async eC.execute (/code/node_modules/.pnpm/next@14.2.13_@playwright+test@1.47.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27552) {
  code: 'ERR_JWT_EXPIRED',
  claim: 'exp',
  reason: 'check_failed'
}
```

@wgraef perhaps this is related to the way we make the LXCat demo available to the outside world? Thanks to @Dale-Muccignat for finding this issue!

**Comment by Dale-Muccignat** [comment]
Can confirm this works now on my end!

```
curl "https://demo.lxcat.net/api/scat-css" -H "Authorization: Bearer $test"
[{"id":"15633241","name":"Ar"},{"id":"15633672","name":"CO"},{"id":"15635021","name":"CO2"},{"id":"15635727","name":"H2"},{"id":"15636213","name":"He"},{"id":"15636376","name":"Mg"},{"id":"15636992","name":"N2"},{"id":"15637750","name":"Na"},{"id":"15638402","name":"NO"},{"id":"15638954","name":"O2"},{"id":"15639502","name":"SF6"},{"id":"15640911","name":"CO"},{"id":"15643889","name":"CO2"},{"id":"15648616","name":"H2"},{"id":"15653484","name":"H2-vib"},{"id":"15663196","name":"N2"},{"id":"15665806","name":"N2-rot"},{"id":"15668020","name":"N2-vib"},{"id":"15674048","name":"O2"},{"id":"15675456","name":"O2-rot"},{"id":"15742657","name":"O2-vib"}]
```

**Comment by daanboer** [comment]
> Can confirm this works now on my end!
> 
> ```
> curl "https://demo.lxcat.net/api/scat-css" -H "Authorization: Bearer $test"
> [{"id":"15633241","name":"Ar"},{"id":"15633672","name":"CO"},{"id":"15635021","name":"CO2"},{"id":"15635727","name":"H2"},{"id":"15636213","name":"He"},{"id":"15636376","name":"Mg"},{"id":"15636992","name":"N2"},{"id":"15637750","name":"Na"},{"id":"15638402","name":"NO"},{"id":"15638954","name":"O2"},{"id":"15639502","name":"SF6"},{"id":"15640911","name":"CO"},{"id":"15643889","name":"CO2"},{"id":"15648616","name":"H2"},{"id":"15653484","name":"H2-vib"},{"id":"15663196","name":"N2"},{"id":"15665806","name":"N2-rot"},{"id":"15668020","name":"N2-vib"},{"id":"15674048","name":"O2"},{"id":"15675456","name":"O2-rot"},{"id":"15742657","name":"O2-vib"}]
> ```

Great! I can reach the protected endpoints as well, so I will close this issue. Thanks to @wgraef for fixing.
